### ISSUE TITLE
Sometimes cannot dismount USB drives

### ISSUE THREAD

**Issue by steve6375** [DavidBrenner3/VMUB#4]
I have noticed recently that VMUB cannot dismount the USB drive even if I retry numerous times.
I suspect this is due to a recent Windows update (I have 1803) or perhaps other change because it always used to work without a problem.
Using tools like 'What is locking this folder' just shows 'System' process accessing the drive.
The Windows SysTray 'Safely Remove' icon also will NOT work on the drive and refuses to unmount it.
The 'USB Disk Eject' application does manage to eject the USB drive though when the SysTray 'Safely Remove' does not work.
I have Comodo AV installed and Windows Defender is disabled.
This problem does not always happen, but is does happen very often.

The funny thing is, if I click **Ignore** on the VMUB pop-up, it often (but not always) then boots to the USB drive via Virtual Box OK   BUT I can the quit VB and run VMUB again and this time it does work and VMUB dismounts the drive correctly.
So recently I have been using VMUB - Ignore - quit VB - VMUB ....   each time I need to boot.

I was wondering if whatever you do when I select 'Ignore' can always be done first, before you attempt to fully lock/dismount the USB drive? It's curious that 'Ignore' + VB seems to do 'something' which then 'releases' the drive for the next attempt.

**Comment by DavidBrenner3** [comment]
Hi,

Yes, the problem seems to be specific to Windows 10 and its updates.
It could be a newly added system process or an old one loaded in a different way.

'Ignore' is dismounting the drive "cutting" all connections to apps/processes accessing the drive.
It's not suppose to be used every time because sometimes it will generate system instability and file system corruption on the drive.
Instead the user should debug and find info about the system process preventing the dismount.

Well, let's try to debug: please use this [utility](http://www.nirsoft.net/utils/opened_files_view.html)
to find out which system process is the culprit.

And post the results here please.

**Comment by steve6375** [comment]
Ah OK - I didn't understand that, now it makes sense why it ignore fixes it - so 'ignore' = 'force dismount'

I will try the utility, but as luck would have it, even though I have had this issue fairly consistently for a month or so, I don't seem to be getting the issue today!

**Comment by DavidBrenner3** [comment]
I experienced sometimes the issue by plugging the drive in the USB port and not using it for a while.
This way Windows and/or some utilities  (like an antivirus) will "think" they can start background processes on the files/folders (from the volumes on drive).
For example indexing and antivirus scan.

Anyway I always deactivate indexing by default and it's no problem ignoring/terminating the indexing process.
And the antivirus scan can be stopped from the antivirus GUI.

**Comment by steve6375** [comment]
OK, my  Fixed-disk USB drive is  showing the problem again (it was OK and
then I copied a file to it and then Windows would not let go of it).

It has two partitions H: and J:

Here is only mention if them...

**Comment by DavidBrenner3** [comment]
Have you tried finding the system process with that utility...?

I'm sure you already know but you can use main menu >> View >> Use Quick Filter
Then you can type the path to the volume (for example 'd:\\').
You'll get something like this:
![view](https://user-images.githubusercontent.com/9998134/42549065-e6608d58-84d2-11e8-9461-11ad7c79dc7f.png)

**Comment by steve6375** [comment]
I was waiting for it to show the issue again. Recently, it seems to not
happen so frequently.

The screenshot shows the OpenFilesView - the USB is J: and L: and both show
the same processes - Safely remove does NOT work and Windows refuses to
release the drive.


I then removed the USB drive (pulled it out of the USB port) and then
re-inserted it again...

Here is screen again after a refresh.
This time 'Safely Remove' System Tray works.
The view looks the same to me...

Any ideas?

Steve

**Comment by DavidBrenner3** [comment]
I can't see any image in your post (just like on your previous post I can't see any image too). In fact the only image I can see in this thread is the one I posted.

Have you uploaded the pictures here on github or have you used another host?

**Comment by DavidBrenner3** [comment]
Are you upset somehow?

If I've done something wrong then sorry, although github not displaying any of your images is not my fault...
And sorry for not giving you a solution faster but as you realize:
1. The real problem is from Windows and that system process. All I can do is find a better workaround than forcing the dismount each time. But, if it exists, it would help me if:
2. I would have all available information so viewing the images too.

Thank you.

**Comment by steve6375** [comment]
Hi
Sorry for not replying. Due to:
1. Very busy with other family matters at the moment
2. Trying to reproduce the problem (which comes and goes) and then running tests to kill processes to see if I can get a better grip on the problem. I really have no idea what is causing it. If I use OpenFileView and kill all processes shown for the USB drive (same as in your screenhot), Windows still will not Safely Remove the USB drive. So something is obviously locking it but I have no idea what!
The screenshots I sent you don't really help as the OpenFileView snapshot of a 'dismountable' drive shows the same open files for a non-dismountable drive. So I have had no clues to give you about where the problem might lie. I am running Comodo AV and I may try uninstalling it for a few days... Please be patient and I will try to investigate more.

**Comment by DavidBrenner3** [comment]
I use Comodo Internet Security Premium 10 now but no such problem.
Oh, the Auto-Containment is set to off - if I won't disable it it would virtualize VMUB every time I recompile and test the latest changes in code.
But it's a good idea trying to uninstall it too.

You should try this app too: https://safelyremove.com/index.htm
It may show the process preventing the dismount.

Sorry, I was inpatient just because I was upset I can't help you (yet)...

**Comment by steve6375** [comment]
closing as  I have not seen this issue for many months now.
